[2024-06-18T17:34:00.765+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:34:00.806+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-18T11:48:55.277694+00:00 [queued]>
[2024-06-18T17:34:00.821+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail manual__2024-06-18T11:48:55.277694+00:00 [queued]>
[2024-06-18T17:34:00.822+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T17:34:00.899+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 11:48:55.277694+00:00
[2024-06-18T17:34:00.904+0545] {standard_task_runner.py:63} INFO - Started process 26427 to run task
[2024-06-18T17:34:00.908+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'manual__2024-06-18T11:48:55.277694+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpc6z56le1']
[2024-06-18T17:34:00.912+0545] {standard_task_runner.py:91} INFO - Job 121: Subtask send_mail
[2024-06-18T17:34:01.064+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail manual__2024-06-18T11:48:55.277694+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T17:34:01.363+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:48:55.277694+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T11:48:55.277694+00:00'
[2024-06-18T17:34:01.365+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:34:01.407+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T17:34:01.407+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-06-18T17:34:01.408+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T17:34:01.436+0545] {email.py:282} INFO - Sent an alert email to ['susmapant@gmail.com']
[2024-06-18T17:34:01.472+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:34:01.494+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=send_mail, run_id=manual__2024-06-18T11:48:55.277694+00:00, execution_date=20240618T114855, start_date=20240618T114900, end_date=20240618T114901
[2024-06-18T17:34:01.683+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T17:34:01.734+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T17:34:01.735+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
