[2024-06-18T17:33:57.222+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:33:57.258+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T11:48:55.277694+00:00 [queued]>
[2024-06-18T17:33:57.287+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task manual__2024-06-18T11:48:55.277694+00:00 [queued]>
[2024-06-18T17:33:57.287+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T17:33:57.372+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 11:48:55.277694+00:00
[2024-06-18T17:33:57.381+0545] {standard_task_runner.py:63} INFO - Started process 26419 to run task
[2024-06-18T17:33:57.390+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'manual__2024-06-18T11:48:55.277694+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmpukx88e3l']
[2024-06-18T17:33:57.396+0545] {standard_task_runner.py:91} INFO - Job 119: Subtask backup_task
[2024-06-18T17:33:57.550+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task manual__2024-06-18T11:48:55.277694+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T17:33:57.805+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:48:55.277694+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T11:48:55.277694+00:00'
[2024-06-18T17:33:57.806+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:33:57.823+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T17:33:57.823+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/manisha/airflow/bashScripts/backup.sh ']
[2024-06-18T17:33:57.835+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T17:33:57.840+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T17:33:57.849+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T17:33:58.163+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T17:33:58.166+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:33:58.311+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=manual__2024-06-18T11:48:55.277694+00:00, execution_date=20240618T114855, start_date=20240618T114857, end_date=20240618T114858
[2024-06-18T17:33:58.486+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T17:33:58.530+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T17:33:58.588+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
