[2024-06-18T17:35:01.446+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:35:01.592+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T11:40:00+00:00 [None]>
[2024-06-18T17:35:01.611+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T11:40:00+00:00 [None]>
[2024-06-18T17:35:01.612+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T17:35:02.057+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 11:40:00+00:00
[2024-06-18T17:35:02.066+0545] {standard_task_runner.py:63} INFO - Started process 26474 to run task
[2024-06-18T17:35:02.079+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T11:40:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp001qg6r3']
[2024-06-18T17:35:02.086+0545] {standard_task_runner.py:91} INFO - Job 122: Subtask backup_task
[2024-06-18T17:35:02.338+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T11:40:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T17:35:02.777+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T11:40:00+00:00'
[2024-06-18T17:35:02.778+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:35:02.795+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T17:35:02.797+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/manisha/airflow/bashScripts/backup.sh ']
[2024-06-18T17:35:02.807+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T17:35:02.814+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T17:35:02.821+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T17:35:03.329+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T17:35:03.330+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:35:03.469+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T11:40:00+00:00, execution_date=20240618T114000, start_date=20240618T115001, end_date=20240618T115003
[2024-06-18T17:35:03.615+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T17:35:03.643+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T17:35:03.644+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T17:40:13.369+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T17:40:13.434+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T11:40:00+00:00 [queued]>
[2024-06-18T17:40:13.443+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T11:40:00+00:00 [queued]>
[2024-06-18T17:40:13.443+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T17:40:13.665+0545] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): backup_task> on 2024-06-18 11:40:00+00:00
[2024-06-18T17:40:13.675+0545] {standard_task_runner.py:63} INFO - Started process 26873 to run task
[2024-06-18T17:40:13.684+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'backup_task', 'scheduled__2024-06-18T11:40:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp7b8ydldy']
[2024-06-18T17:40:13.689+0545] {standard_task_runner.py:91} INFO - Job 133: Subtask backup_task
[2024-06-18T17:40:14.033+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.backup_task scheduled__2024-06-18T11:40:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T17:40:14.290+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='backup_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T11:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T11:40:00+00:00'
[2024-06-18T17:40:14.290+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T17:40:14.310+0545] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-18T17:40:14.311+0545] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/manisha/airflow/bashScripts/backup.sh ']
[2024-06-18T17:40:14.316+0545] {subprocess.py:86} INFO - Output:
[2024-06-18T17:40:14.320+0545] {subprocess.py:93} INFO - mysqldump: [Warning] Using a password on the command line interface can be insecure.
[2024-06-18T17:40:14.325+0545] {subprocess.py:93} INFO - mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
[2024-06-18T17:40:14.512+0545] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-18T17:40:14.513+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T17:40:14.616+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=backup_task, run_id=scheduled__2024-06-18T11:40:00+00:00, execution_date=20240618T114000, start_date=20240618T115513, end_date=20240618T115514
[2024-06-18T17:40:14.740+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T17:40:14.804+0545] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T17:40:14.873+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
