[2024-06-18T16:25:06.932+0545] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T16:25:06.956+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T10:30:00+00:00 [queued]>
[2024-06-18T16:25:06.964+0545] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T10:30:00+00:00 [queued]>
[2024-06-18T16:25:06.965+0545] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T16:25:07.100+0545] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_mail> on 2024-06-18 10:30:00+00:00
[2024-06-18T16:25:07.109+0545] {standard_task_runner.py:63} INFO - Started process 23659 to run task
[2024-06-18T16:25:07.115+0545] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Backup_Database', 'send_mail', 'scheduled__2024-06-18T10:30:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/basic_dag.py', '--cfg-path', '/tmp/tmp62l5dvsm']
[2024-06-18T16:25:07.116+0545] {standard_task_runner.py:91} INFO - Job 100: Subtask send_mail
[2024-06-18T16:25:07.325+0545] {task_command.py:426} INFO - Running <TaskInstance: Backup_Database.send_mail scheduled__2024-06-18T10:30:00+00:00 [running]> on host manisha-Inspiron-3580
[2024-06-18T16:25:07.699+0545] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='manisha' AIRFLOW_CTX_DAG_ID='Backup_Database' AIRFLOW_CTX_TASK_ID='send_mail' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T10:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T10:30:00+00:00'
[2024-06-18T16:25:07.700+0545] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T16:25:07.733+0545] {logging_mixin.py:188} WARNING - /home/manisha/airflow_env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-06-18T16:25:07.734+0545] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-06-18T16:25:07.734+0545] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-18T16:25:07.752+0545] {email.py:282} INFO - Sent an alert email to ['manishakhadka228@gmail.com']
[2024-06-18T16:25:07.813+0545] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T16:25:07.855+0545] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Backup_Database, task_id=send_mail, run_id=scheduled__2024-06-18T10:30:00+00:00, execution_date=20240618T103000, start_date=20240618T104006, end_date=20240618T104007
[2024-06-18T16:25:08.051+0545] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T16:25:08.106+0545] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T16:25:08.107+0545] {local_task_job_runner.py:222} INFO - ::endgroup::
